/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppVisualizeRouteImport } from './routes/_app/visualize'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppTestsRouteImport } from './routes/_app/tests'
import { Route as AppLabsRouteImport } from './routes/_app/labs'
import { Route as AppIdentifyRouteImport } from './routes/_app/identify'
import { Route as AppHamiverseRouteImport } from './routes/_app/hamiverse'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppAppearanceRouteImport } from './routes/_app/appearance'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/_app/_authenticated/route'
import { Route as ApiPublicQuestionsRouteImport } from './routes/api/public/questions'
import { Route as AppCommunityGroupIdRouteImport } from './routes/_app/community.$groupId'
import { Route as AppAuthenticatedScheduleRouteImport } from './routes/_app/_authenticated/schedule'
import { Route as AppAuthenticatedProgressRouteImport } from './routes/_app/_authenticated/progress'
import { Route as AppAuthenticatedProfileRouteImport } from './routes/_app/_authenticated/profile'
import { Route as AppAuthenticatedNotesRouteImport } from './routes/_app/_authenticated/notes'
import { Route as AppAuthenticatedStudySubjectRouteImport } from './routes/_app/_authenticated/study.$subject'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisualizeRoute = AppVisualizeRouteImport.update({
  id: '/visualize',
  path: '/visualize',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLabsRoute = AppLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIdentifyRoute = AppIdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHamiverseRoute = AppHamiverseRouteImport.update({
  id: '/hamiverse',
  path: '/hamiverse',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppearanceRoute = AppAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiPublicQuestionsRoute = ApiPublicQuestionsRouteImport.update({
  id: '/api/public/questions',
  path: '/api/public/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityGroupIdRoute = AppCommunityGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppCommunityRoute,
} as any)
const AppAuthenticatedScheduleRoute =
  AppAuthenticatedScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedProgressRoute =
  AppAuthenticatedProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedProfileRoute = AppAuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedNotesRoute = AppAuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedStudySubjectRoute =
  AppAuthenticatedStudySubjectRouteImport.update({
    id: '/study/$subject',
    path: '/study/$subject',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/appearance': typeof AppAppearanceRoute
  '/community': typeof AppCommunityRouteWithChildren
  '/courses': typeof AppCoursesRoute
  '/dashboard': typeof AppDashboardRoute
  '/hamiverse': typeof AppHamiverseRoute
  '/identify': typeof AppIdentifyRoute
  '/labs': typeof AppLabsRoute
  '/tests': typeof AppTestsRoute
  '/tutor': typeof AppTutorRoute
  '/visualize': typeof AppVisualizeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/join/$token': typeof JoinTokenRoute
  '/notes': typeof AppAuthenticatedNotesRoute
  '/profile': typeof AppAuthenticatedProfileRoute
  '/progress': typeof AppAuthenticatedProgressRoute
  '/schedule': typeof AppAuthenticatedScheduleRoute
  '/community/$groupId': typeof AppCommunityGroupIdRoute
  '/api/public/questions': typeof ApiPublicQuestionsRoute
  '/study/$subject': typeof AppAuthenticatedStudySubjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/appearance': typeof AppAppearanceRoute
  '/community': typeof AppCommunityRouteWithChildren
  '/courses': typeof AppCoursesRoute
  '/dashboard': typeof AppDashboardRoute
  '/hamiverse': typeof AppHamiverseRoute
  '/identify': typeof AppIdentifyRoute
  '/labs': typeof AppLabsRoute
  '/tests': typeof AppTestsRoute
  '/tutor': typeof AppTutorRoute
  '/visualize': typeof AppVisualizeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/join/$token': typeof JoinTokenRoute
  '/notes': typeof AppAuthenticatedNotesRoute
  '/profile': typeof AppAuthenticatedProfileRoute
  '/progress': typeof AppAuthenticatedProgressRoute
  '/schedule': typeof AppAuthenticatedScheduleRoute
  '/community/$groupId': typeof AppCommunityGroupIdRoute
  '/api/public/questions': typeof ApiPublicQuestionsRoute
  '/study/$subject': typeof AppAuthenticatedStudySubjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/_app/appearance': typeof AppAppearanceRoute
  '/_app/community': typeof AppCommunityRouteWithChildren
  '/_app/courses': typeof AppCoursesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hamiverse': typeof AppHamiverseRoute
  '/_app/identify': typeof AppIdentifyRoute
  '/_app/labs': typeof AppLabsRoute
  '/_app/tests': typeof AppTestsRoute
  '/_app/tutor': typeof AppTutorRoute
  '/_app/visualize': typeof AppVisualizeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/join/$token': typeof JoinTokenRoute
  '/_app/_authenticated/notes': typeof AppAuthenticatedNotesRoute
  '/_app/_authenticated/profile': typeof AppAuthenticatedProfileRoute
  '/_app/_authenticated/progress': typeof AppAuthenticatedProgressRoute
  '/_app/_authenticated/schedule': typeof AppAuthenticatedScheduleRoute
  '/_app/community/$groupId': typeof AppCommunityGroupIdRoute
  '/api/public/questions': typeof ApiPublicQuestionsRoute
  '/_app/_authenticated/study/$subject': typeof AppAuthenticatedStudySubjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/appearance'
    | '/community'
    | '/courses'
    | '/dashboard'
    | '/hamiverse'
    | '/identify'
    | '/labs'
    | '/tests'
    | '/tutor'
    | '/visualize'
    | '/api/chat'
    | '/api/generate-image'
    | '/join/$token'
    | '/notes'
    | '/profile'
    | '/progress'
    | '/schedule'
    | '/community/$groupId'
    | '/api/public/questions'
    | '/study/$subject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/appearance'
    | '/community'
    | '/courses'
    | '/dashboard'
    | '/hamiverse'
    | '/identify'
    | '/labs'
    | '/tests'
    | '/tutor'
    | '/visualize'
    | '/api/chat'
    | '/api/generate-image'
    | '/join/$token'
    | '/notes'
    | '/profile'
    | '/progress'
    | '/schedule'
    | '/community/$groupId'
    | '/api/public/questions'
    | '/study/$subject'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/_authenticated'
    | '/_app/appearance'
    | '/_app/community'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/hamiverse'
    | '/_app/identify'
    | '/_app/labs'
    | '/_app/tests'
    | '/_app/tutor'
    | '/_app/visualize'
    | '/api/chat'
    | '/api/generate-image'
    | '/join/$token'
    | '/_app/_authenticated/notes'
    | '/_app/_authenticated/profile'
    | '/_app/_authenticated/progress'
    | '/_app/_authenticated/schedule'
    | '/_app/community/$groupId'
    | '/api/public/questions'
    | '/_app/_authenticated/study/$subject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiPublicQuestionsRoute: typeof ApiPublicQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/visualize': {
      id: '/_app/visualize'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof AppVisualizeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tests': {
      id: '/_app/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/labs': {
      id: '/_app/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof AppLabsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/identify': {
      id: '/_app/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof AppIdentifyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/hamiverse': {
      id: '/_app/hamiverse'
      path: '/hamiverse'
      fullPath: '/hamiverse'
      preLoaderRoute: typeof AppHamiverseRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/appearance': {
      id: '/_app/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppAppearanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/public/questions': {
      id: '/api/public/questions'
      path: '/api/public/questions'
      fullPath: '/api/public/questions'
      preLoaderRoute: typeof ApiPublicQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/community/$groupId': {
      id: '/_app/community/$groupId'
      path: '/$groupId'
      fullPath: '/community/$groupId'
      preLoaderRoute: typeof AppCommunityGroupIdRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/_app/_authenticated/schedule': {
      id: '/_app/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppAuthenticatedScheduleRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/progress': {
      id: '/_app/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppAuthenticatedProgressRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/profile': {
      id: '/_app/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAuthenticatedProfileRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/notes': {
      id: '/_app/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppAuthenticatedNotesRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/study/$subject': {
      id: '/_app/_authenticated/study/$subject'
      path: '/study/$subject'
      fullPath: '/study/$subject'
      preLoaderRoute: typeof AppAuthenticatedStudySubjectRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedNotesRoute: typeof AppAuthenticatedNotesRoute
  AppAuthenticatedProfileRoute: typeof AppAuthenticatedProfileRoute
  AppAuthenticatedProgressRoute: typeof AppAuthenticatedProgressRoute
  AppAuthenticatedScheduleRoute: typeof AppAuthenticatedScheduleRoute
  AppAuthenticatedStudySubjectRoute: typeof AppAuthenticatedStudySubjectRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedNotesRoute: AppAuthenticatedNotesRoute,
  AppAuthenticatedProfileRoute: AppAuthenticatedProfileRoute,
  AppAuthenticatedProgressRoute: AppAuthenticatedProgressRoute,
  AppAuthenticatedScheduleRoute: AppAuthenticatedScheduleRoute,
  AppAuthenticatedStudySubjectRoute: AppAuthenticatedStudySubjectRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppCommunityRouteChildren {
  AppCommunityGroupIdRoute: typeof AppCommunityGroupIdRoute
}

const AppCommunityRouteChildren: AppCommunityRouteChildren = {
  AppCommunityGroupIdRoute: AppCommunityGroupIdRoute,
}

const AppCommunityRouteWithChildren = AppCommunityRoute._addFileChildren(
  AppCommunityRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppAppearanceRoute: typeof AppAppearanceRoute
  AppCommunityRoute: typeof AppCommunityRouteWithChildren
  AppCoursesRoute: typeof AppCoursesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHamiverseRoute: typeof AppHamiverseRoute
  AppIdentifyRoute: typeof AppIdentifyRoute
  AppLabsRoute: typeof AppLabsRoute
  AppTestsRoute: typeof AppTestsRoute
  AppTutorRoute: typeof AppTutorRoute
  AppVisualizeRoute: typeof AppVisualizeRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppAppearanceRoute: AppAppearanceRoute,
  AppCommunityRoute: AppCommunityRouteWithChildren,
  AppCoursesRoute: AppCoursesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHamiverseRoute: AppHamiverseRoute,
  AppIdentifyRoute: AppIdentifyRoute,
  AppLabsRoute: AppLabsRoute,
  AppTestsRoute: AppTestsRoute,
  AppTutorRoute: AppTutorRoute,
  AppVisualizeRoute: AppVisualizeRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiPublicQuestionsRoute: ApiPublicQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
