/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppTestsRouteImport } from './routes/_app/tests'
import { Route as AppSyllabusRouteImport } from './routes/_app/syllabus'
import { Route as AppLabsRouteImport } from './routes/_app/labs'
import { Route as AppIdentifyRouteImport } from './routes/_app/identify'
import { Route as AppHamiverseRouteImport } from './routes/_app/hamiverse'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/_app/_authenticated/route'
import { Route as AppAuthenticatedScheduleRouteImport } from './routes/_app/_authenticated/schedule'
import { Route as AppAuthenticatedProfileRouteImport } from './routes/_app/_authenticated/profile'
import { Route as AppAuthenticatedNotesRouteImport } from './routes/_app/_authenticated/notes'
import { Route as AppAuthenticatedCommunityRouteImport } from './routes/_app/_authenticated/community'
import { Route as AppAuthenticatedCommunityGroupIdRouteImport } from './routes/_app/_authenticated/community.$groupId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSyllabusRoute = AppSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLabsRoute = AppLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIdentifyRoute = AppIdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHamiverseRoute = AppHamiverseRouteImport.update({
  id: '/hamiverse',
  path: '/hamiverse',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedScheduleRoute =
  AppAuthenticatedScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedProfileRoute = AppAuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedNotesRoute = AppAuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedCommunityRoute =
  AppAuthenticatedCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedCommunityGroupIdRoute =
  AppAuthenticatedCommunityGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AppAuthenticatedCommunityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/hamiverse': typeof AppHamiverseRoute
  '/identify': typeof AppIdentifyRoute
  '/labs': typeof AppLabsRoute
  '/syllabus': typeof AppSyllabusRoute
  '/tests': typeof AppTestsRoute
  '/tutor': typeof AppTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/community': typeof AppAuthenticatedCommunityRouteWithChildren
  '/notes': typeof AppAuthenticatedNotesRoute
  '/profile': typeof AppAuthenticatedProfileRoute
  '/schedule': typeof AppAuthenticatedScheduleRoute
  '/community/$groupId': typeof AppAuthenticatedCommunityGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/hamiverse': typeof AppHamiverseRoute
  '/identify': typeof AppIdentifyRoute
  '/labs': typeof AppLabsRoute
  '/syllabus': typeof AppSyllabusRoute
  '/tests': typeof AppTestsRoute
  '/tutor': typeof AppTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/community': typeof AppAuthenticatedCommunityRouteWithChildren
  '/notes': typeof AppAuthenticatedNotesRoute
  '/profile': typeof AppAuthenticatedProfileRoute
  '/schedule': typeof AppAuthenticatedScheduleRoute
  '/community/$groupId': typeof AppAuthenticatedCommunityGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hamiverse': typeof AppHamiverseRoute
  '/_app/identify': typeof AppIdentifyRoute
  '/_app/labs': typeof AppLabsRoute
  '/_app/syllabus': typeof AppSyllabusRoute
  '/_app/tests': typeof AppTestsRoute
  '/_app/tutor': typeof AppTutorRoute
  '/api/chat': typeof ApiChatRoute
  '/join/$token': typeof JoinTokenRoute
  '/_app/_authenticated/community': typeof AppAuthenticatedCommunityRouteWithChildren
  '/_app/_authenticated/notes': typeof AppAuthenticatedNotesRoute
  '/_app/_authenticated/profile': typeof AppAuthenticatedProfileRoute
  '/_app/_authenticated/schedule': typeof AppAuthenticatedScheduleRoute
  '/_app/_authenticated/community/$groupId': typeof AppAuthenticatedCommunityGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/hamiverse'
    | '/identify'
    | '/labs'
    | '/syllabus'
    | '/tests'
    | '/tutor'
    | '/api/chat'
    | '/join/$token'
    | '/community'
    | '/notes'
    | '/profile'
    | '/schedule'
    | '/community/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/hamiverse'
    | '/identify'
    | '/labs'
    | '/syllabus'
    | '/tests'
    | '/tutor'
    | '/api/chat'
    | '/join/$token'
    | '/community'
    | '/notes'
    | '/profile'
    | '/schedule'
    | '/community/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/_authenticated'
    | '/_app/dashboard'
    | '/_app/hamiverse'
    | '/_app/identify'
    | '/_app/labs'
    | '/_app/syllabus'
    | '/_app/tests'
    | '/_app/tutor'
    | '/api/chat'
    | '/join/$token'
    | '/_app/_authenticated/community'
    | '/_app/_authenticated/notes'
    | '/_app/_authenticated/profile'
    | '/_app/_authenticated/schedule'
    | '/_app/_authenticated/community/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tests': {
      id: '/_app/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/syllabus': {
      id: '/_app/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof AppSyllabusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/labs': {
      id: '/_app/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof AppLabsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/identify': {
      id: '/_app/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof AppIdentifyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/hamiverse': {
      id: '/_app/hamiverse'
      path: '/hamiverse'
      fullPath: '/hamiverse'
      preLoaderRoute: typeof AppHamiverseRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated/schedule': {
      id: '/_app/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppAuthenticatedScheduleRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/profile': {
      id: '/_app/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAuthenticatedProfileRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/notes': {
      id: '/_app/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppAuthenticatedNotesRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/community': {
      id: '/_app/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppAuthenticatedCommunityRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/community/$groupId': {
      id: '/_app/_authenticated/community/$groupId'
      path: '/$groupId'
      fullPath: '/community/$groupId'
      preLoaderRoute: typeof AppAuthenticatedCommunityGroupIdRouteImport
      parentRoute: typeof AppAuthenticatedCommunityRoute
    }
  }
}

interface AppAuthenticatedCommunityRouteChildren {
  AppAuthenticatedCommunityGroupIdRoute: typeof AppAuthenticatedCommunityGroupIdRoute
}

const AppAuthenticatedCommunityRouteChildren: AppAuthenticatedCommunityRouteChildren =
  {
    AppAuthenticatedCommunityGroupIdRoute:
      AppAuthenticatedCommunityGroupIdRoute,
  }

const AppAuthenticatedCommunityRouteWithChildren =
  AppAuthenticatedCommunityRoute._addFileChildren(
    AppAuthenticatedCommunityRouteChildren,
  )

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedCommunityRoute: typeof AppAuthenticatedCommunityRouteWithChildren
  AppAuthenticatedNotesRoute: typeof AppAuthenticatedNotesRoute
  AppAuthenticatedProfileRoute: typeof AppAuthenticatedProfileRoute
  AppAuthenticatedScheduleRoute: typeof AppAuthenticatedScheduleRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedCommunityRoute: AppAuthenticatedCommunityRouteWithChildren,
  AppAuthenticatedNotesRoute: AppAuthenticatedNotesRoute,
  AppAuthenticatedProfileRoute: AppAuthenticatedProfileRoute,
  AppAuthenticatedScheduleRoute: AppAuthenticatedScheduleRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHamiverseRoute: typeof AppHamiverseRoute
  AppIdentifyRoute: typeof AppIdentifyRoute
  AppLabsRoute: typeof AppLabsRoute
  AppSyllabusRoute: typeof AppSyllabusRoute
  AppTestsRoute: typeof AppTestsRoute
  AppTutorRoute: typeof AppTutorRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHamiverseRoute: AppHamiverseRoute,
  AppIdentifyRoute: AppIdentifyRoute,
  AppLabsRoute: AppLabsRoute,
  AppSyllabusRoute: AppSyllabusRoute,
  AppTestsRoute: AppTestsRoute,
  AppTutorRoute: AppTutorRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
